version: '3.9'

services:
  container1:
    image: mpandey9/container1:latest
    ports:
      - 6000:6000

  container2:
    image: mpandey9/container2:latest
    ports:
      - 7000:7000
    volumes:
      - .:/Users/mayankpandey/IdeaProjects/mpandey/A1